name = "cf-dh"
main = "src/index.js"
compatibility_date = "2026-07-07"
account_id = "677f9e4ae3fa2bb512634405f86f124c"
workers_dev = true

[vars]
ADMIN_PASSWORD = "admin123"

[[kv_namespaces]]
binding = "NAVIGATION_DATA"
id = "0c169485521e40fab8289575a028026b"
